USE reddit-exam;
CREATE TABLE Customers (
  ID INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL
);
CREATE TABLE Customer_Addresses(
  ID INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT(5) NOT NULL,
  STREET_ADDRESS VARCHAR(20),
  POSTAL_CODE VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(2) NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES Customers(ID)
);
INSERT INTO Customers (NAME) VALUES ('Ryan'), ('Jon'), ('Imran'), ('Betty');
INSERT INTO Customer_Addresses (CUSTOMER_ID, STREET_ADDRESS, POSTAL_CODE, COUNTRY) VALUES (1, '999 Night Stalker Road', '12345', 'US'), (2, '123 Big Walk Way', '75023', 'US'), (3, '', '90021', 'US');