CREATE TABLE Customers (
  ID INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL
);
CREATE TABLE Customer_Addresses(
  ID INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT(5) NOT NULL,
  STREET_ADDRESS VARCHAR(20),
  POSTAL_CODE VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(2) NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES Customers(ID)
);
INSERT INTO CUSTOMER